apiVersion: apiserver.config.k8s.io/v1
kind: EncryptionConfiguration
resources:
  - resources:
      - secrets
    providers:
      - kms:
          apiVersion: v2
          name: GCPSecretManager
          endpoint: unix:///var/run/k8splugin.sock
          timeout: 3s
      - identity: {}
